---
name: "uncertainty_total_base"
period: "week"
steps: 260
runs: 100
sim_details:
  germinationStation:
    germination_costs:
      cost_per_seed: 0.11471
      seeds_per_shelf: 400
      new_shelf_capex: 108.6
      shelf_running_cost: 1.03488
      new_shelving_unit_capex: 55
      shelves_per_shelving_unit: 6
      extra_production: 3.5
    plant_maturity:
      weeks2mature: 3
      mature_life: 2
    initial_shelf_counts: [20, 120]
    active_varieties: 5
  cac:
    cac_low:
      name: "gaussian"
      parameters:
        loc: 212.53
        scale: 20
    cac_med:
      name: "gaussian"
      parameters:
        loc: 118.40
        scale: 15
    cac_high:
      name: "gaussian"
      parameters:
        loc: 89.97
        scale: 10
  activeClients:
    distributions:
      unit:
        name: "skew-norm"
        parameters:
          a: -4
          loc: 6
          scale: 2
      subLength:
        name: "constant"
        parameters:
          value: 4
      officePosition:
        name: "beta"
        parameters:
          a: 1
          b: 1
          loc: 0
          scale: 10
      churn:
        name: "binomial"
        parameters:
          p: 0.00833
      plantDist:
        name: "discreteBeta"
        parameters:
          alpha: 1
          beta: 1
          # buckets should be the same as active varieties
          buckets: 5
    plant_request_length: 12
    client_details:
      subscription_price: 40
      purchase_price: 500
      plants_per_unit: 30
      initial_contract_period: 52
    cac:
      thresholds: [5, 10, 25]
  customerAcquisition:
    lead_generation:
      name: "skew-norm"
      parameters:
        a: -4
        loc: 20
        scale: 5
    conversion:
      name: "binomial"
      parameters:
        p: 0.07
  build:
    man_cost: [[63.53, 47.88, 41.90], 31.76]
    mat_cost: [[203.68, 169.01, 146.58], 105.86]
    # reman_cost: [[87.10, 48.36, 42.70], 24.70]
    build_thresholds: [10, 20, 50]
    phase: 1
  install:
    install_cost: 12.5
  maintenance:
    maintenance_cost: 7.038
  transport:
    hq_position:
      name: "beta"
      parameters:
        a: 1
        b: 1
        loc: 0
        scale: 5
    fuel_cost: 0.22
    max_clients_serviced: 5
  op_cost:
    op_cost_dist:
      name: gaussian
      parameters:
        loc: 2000
        scale: 500






